# sound
top_small = r'12'' Fullrange Lautsprecher'
top_big = r'15'' Fullrange Lautsprecher'
sub = r'Doppel 12'' Subwoofer'
mic_cable = 'Mikrofon (Kabel)'
mic_wireless = 'Mikrofon (Funk)'

# light
ali_pair = '18x18W RGBWAUV Uplight IP 65'
led_bar = 'LED Bar'
superfly  = '2in1 Derby-Effekt & Strobe-LED Superfly'
light_pole = 'Lichtstativ T-Träger'
multi_fx_bar = 'Multi-FX Laser Bar'
light_mixer = 'Lichtmischpult'
traverse_pole = 'Traversenstativ (max. Höhe: 4m)'
traverse_mid = '3m Traverse'
traverse_big = '4,5m Traverse'
laser = 'RGY Laser (Klasse 3R)'
moving_head = 'LED Moving Head'
strobe = 'Stroboskop'
